import './generate-categorized-item-keys'
import './generate-categorized-item-names'
import './generate-champion-ids-by-name'
import './generate-champion-ids'
import './generate-champion-keys'
import './generate-champion-names'
import './generate-item-keys'
import './generate-item-names'
// @deprecated
// import './generate-rune-ids'
// @deprecated
// import './generate-rune-names'
import './generate-rune-picking-relationships'
import './generate-rune-sets-by-rune-names'
import './generate-rune-sets'
import './generate-spell-ids-by-name'
import './generate-spell-ids'
import './generate-spell-keys'
import './generate-spell-names'
// @deprecated
// import './generate-stat-rune-ids'
// @deprecated
// import './generate-stat-rune-names'
import './generate-tree-rune-ids'
import './generate-tree-rune-names'
