export const LegendaryItemNames = [
  'Abyssal Mask',
  'Anathema\'s Chains',
  'Archangel\'s Staff',
  'Ardent Censer',
  'Axiom Arc',
  'Banshee\'s Veil',
  'Black Cleaver',
  'Black Mist Scythe',
  'Blade of The Ruined King',
  'Bloodthirster',
  'Bulwark of the Mountain',
  'Chempunk Chainsword',
  'Chemtech Putrifier',
  'Cosmic Drive',
  'Dead Man\'s Plate',
  'Death\'s Dance',
  'Demonic Embrace',
  'Edge of Night',
  'Essence Reaver',
  'Fimbulwinter',
  'Force of Nature',
  'Frozen Heart',
  'Gargoyle Stoneplate',
  'Guardian Angel',
  'Guinsoo\'s Rageblade',
  'Horizon Focus',
  'Hullbreaker',
  'Infinity Edge',
  'Knight\'s Vow',
  'Lich Bane',
  'Lord Dominik\'s Regards',
  'Manamune',
  'Maw of Malmortius',
  'Mejai\'s Soulstealer',
  'Mercurial Scimitar',
  'Mikael\'s Blessing',
  'Morellonomicon',
  'Mortal Reminder',
  'Muramana',
  'Nashor\'s Tooth',
  'Navori Quickblades',
  'Pauldrons of Whiterock',
  'Phantom Dancer',
  'Rabadon\'s Deathcap',
  'Randuin\'s Omen',
  'Rapid Firecannon',
  'Ravenous Hydra',
  'Redemption',
  'Runaan\'s Hurricane',
  'Rylai\'s Crystal Scepter',
  'Seraph\'s Embrace',
  'Serpent\'s Fang',
  'Serylda\'s Grudge',
  'Shadowflame',
  'Shard of True Ice',
  'Silvermere Dawn',
  'Spirit Visage',
  'Staff of Flowing Water',
  'Sterak\'s Gage',
  'Stormrazor',
  'The Collector',
  'Thornmail',
  'Titanic Hydra',
  'Umbral Glaive',
  'Vigilant Wardstone',
  'Void Staff',
  'Warmog\'s Armor',
  'Winter\'s Approach',
  'Wit\'s End',
  'Youmuu\'s Ghostblade',
  'Zeke\'s Convergence',
  'Zhonya\'s Hourglass',
] as const
